apiVersion: pulumi.com/v1
kind: Program
metadata:
  name: cncf-demo
program:
  resources:
    bucket:
      type: aws:s3:BucketV2
    bucketOwnershipControls:
      type: aws:s3:BucketOwnershipControls
      properties:
        bucket: ${bucket.id}
        rule:
          objectOwnership: BucketOwnerPreferred
    bucketPublicAccessBlock:
      type: aws:s3:BucketPublicAccessBlock
      properties:
        bucket: ${bucket.id}
        blockPublicAcls: false
        blockPublicPolicy: false
        ignorePublicAcls: false
        restrictPublicBuckets: false
    bucketACL:
      type: aws:s3:BucketAclV2
      properties:
        bucket: ${bucket.id}
        acl: public-read
      options:
        dependsOn:
        - ${bucketOwnershipControls}
        - ${bucketPublicAccessBlock}
    webSiteContent:
      type: aws:s3:BucketWebsiteConfigurationV2
      properties:
        bucket: ${bucket.id}
        indexDocument:
          suffix: index.html
    index.html:
      type: aws:s3:BucketObject
      properties:
        bucket: ${bucket.id}
        content: |
          <html>
          <head>
          <title>Hello CNCF Demo Audience!</title>
          </head>
          <body>
          <h1>Hello CNCF Demo Audience!</h1>
          <a href="http://bucket-b287830.s3-website.eu-central-1.amazonaws.com/"> "Click Me!" </a>
          </body>
          </html>
        contentType: text/html
        acl: public-read
  outputs:
    url: http://${webSiteContent.websiteEndpoint}
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: cncf-demo
spec:
  stack: ediri/cncf-demo/dev
  envRefs:
    AWS_ACCESS_KEY_ID:
      type: Secret
      secret:
        name: aws-credentials
        key: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      type: Secret
      secret:
        name: aws-credentials
        key: AWS_SECRET_ACCESS_KEY
  programRef:
    name: cncf-demo
  destroyOnFinalize: false
  config:
    aws:region: eu-central-1
