apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zzz
  description: Stack for zzz
  annotations:
    pulumi.com/project-slug: ediri/zzz/dev
spec:
  owner: infrastructure
  domain: gitops-platform
  type: service
  lifecycle: experimental
  system: gitops-system
