apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-2
  description: Stack for test-2
  annotations:
    pulumi.com/project-slug: dirien/test/dev
spec:
  owner: infrastructure
  domain: gitops-platform
  type: service
  lifecycle: experimental
  system: gitops-system
