apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cncf-demo
  description: Stack for cncf-demo
  annotations:
    pulumi.com/project-slug: dirien/cncf-demo/dev
spec:
  owner: infrastructure
  domain: gitops-platform
  type: service
  lifecycle: experimental
  system: gitops-system
