apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bkv-hello-world
  description: Stack for bkv-hello-world
  annotations:
    pulumi.com/project-slug: ediri/bkv-hello-world/dev
spec:
  owner: infrastructure
  domain: gitops-platform
  type: service
  lifecycle: experimental
  system: gitops-system
