apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: atx-pulumi-pug
  description: Stack for atx-pulumi-pug
  annotations:
    pulumi.com/project-slug: ediri/atx-pulumi-pug/dev
spec:
  owner: infrastructure
  domain: gitops-platform
  type: service
  lifecycle: experimental
  system: gitops-system
